//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admission()
        {
            this.WardRounds = new HashSet<WardRound>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AttID { get; set; }
        public Nullable<int> ClinicWardID { get; set; }
        public string WardName { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public string ActivityType { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string PatientName { get; set; }
        public string Age { get; set; }
        public string Sex { get; set; }
        public string Official { get; set; }
        public string Designation { get; set; }
        public string Dept { get; set; }
        public string Hall { get; set; }
        public string Remark { get; set; }
        public string PostedBy { get; set; }
        public Nullable<int> PostedByID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual attendance attendance { get; set; }
        public virtual ClinicWard ClinicWard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WardRound> WardRounds { get; set; }
    }
}
