//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class analysis
    {
        public long ID { get; set; }
        public string iclass { get; set; }
        public string idetails { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<decimal> iamount { get; set; }
        public string eclass { get; set; }
        public string edetails { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<decimal> eamount { get; set; }
    }
}
