//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anc
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Card_Number { get; set; }
        public string Visit { get; set; }
        public string Parity { get; set; }
        public string BP { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Gestation { get; set; }
        public string FHH { get; set; }
        public string EDD { get; set; }
        public string HB_Reg { get; set; }
        public string HB_36wk { get; set; }
        public string Blood_Group { get; set; }
        public string Sickling { get; set; }
        public string VDLL { get; set; }
        public Nullable<short> PMTCT { get; set; }
        public string ARV { get; set; }
        public string TT { get; set; }
        public Nullable<short> IPT { get; set; }
        public string ITW { get; set; }
        public string Diagnosis { get; set; }
        public string Remark { get; set; }
        public string Referred_To { get; set; }
        public string Risk_Factor { get; set; }
        public string Physician { get; set; }
        public string Cycle { get; set; }
        public string LMP { get; set; }
        public string Gestation_Age { get; set; }
        public string Temp { get; set; }
        public string SFH { get; set; }
        public string HIV { get; set; }
        public string Hep_B { get; set; }
        public string PH { get; set; }
        public string Urine { get; set; }
        public string Presentation { get; set; }
        public string Lie { get; set; }
        public string FHR { get; set; }
    }
}
