//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string Location { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Make { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<System.DateTime> Date_Acquired { get; set; }
        public Nullable<System.DateTime> Date_Sold { get; set; }
        public Nullable<decimal> Purchase_Price { get; set; }
        public Nullable<decimal> Current_Value { get; set; }
        public string Status { get; set; }
        public string Serial_No { get; set; }
        public Nullable<System.DateTime> Next_Maintenance { get; set; }
        public string Comment { get; set; }
        public Nullable<short> Sold { get; set; }
        public Nullable<decimal> Amount_Sold { get; set; }
        public Nullable<decimal> Depreciation { get; set; }
        public Nullable<int> Life_Span { get; set; }
        public Nullable<decimal> Depreciation_Rate { get; set; }
        public string Depreciation_Method { get; set; }
        public Nullable<decimal> Netbook_Value { get; set; }
    }
}
