//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public long ID { get; set; }
        public string Card_Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> Attended { get; set; }
        public string Consultant { get; set; }
        public string Room { get; set; }
        public string Diagnosis { get; set; }
        public string Service_Type { get; set; }
        public string Outcome { get; set; }
        public string Attendance_Type { get; set; }
        public string Age { get; set; }
        public string NHIS_No { get; set; }
        public string Sex { get; set; }
        public string Month { get; set; }
        public string schemeID { get; set; }
        public string Special_Code { get; set; }
        public string Description { get; set; }
        public string Package { get; set; }
        public string Position { get; set; }
    }
}
