//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<bool> Attended { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public string Consultant { get; set; }
        public Nullable<int> ConsultingRoomID { get; set; }
        public string Room { get; set; }
        public string Diagnosis { get; set; }
        public string ServiceType { get; set; }
        public string Outcome { get; set; }
        public string AttendanceType { get; set; }
        public string Age { get; set; }
        public string NHISNo { get; set; }
        public string Sex { get; set; }
        public string Month { get; set; }
        public string SchemeID { get; set; }
        public string SpecialCode { get; set; }
        public string Description { get; set; }
        public string Package { get; set; }
        public string Position { get; set; }
    }
}
