//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank
    {
        public int BankID { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
        public Nullable<short> Online { get; set; }
        public string Location { get; set; }
        public string BankCode { get; set; }
    }
}
