//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billupdate
    {
        public long ID { get; set; }
        public string Transaction_Type { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<long> Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Cashier { get; set; }
    }
}
