//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public long ID { get; set; }
        public string Card_Number { get; set; }
        public string Patient_Name { get; set; }
        public string NHIS_Number { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Company_Name { get; set; }
        public string Category { get; set; }
        public string Cashier { get; set; }
        public string Bill_Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Amount_Paid { get; set; }
        public string Transaction_Type { get; set; }
        public string Details { get; set; }
        public string Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<short> Paid { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Doctor { get; set; }
    }
}
