//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string CardNumber { get; set; }
        public string PatientName { get; set; }
        public string NHISNumber { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CompanyName { get; set; }
        public string Category { get; set; }
        public string Cashier { get; set; }
        public Nullable<int> BillTypeID { get; set; }
        public string BillType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string TransactionType { get; set; }
        public string Details { get; set; }
        public string Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<short> Paid { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Doctor { get; set; }
        public Nullable<int> DoctorID { get; set; }
    }
}
