//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class biovital
    {
        public long ID { get; set; }
        public string Card_Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string BP { get; set; }
        public string Fasting { get; set; }
        public string Mass { get; set; }
        public Nullable<long> AttID { get; set; }
        public string Taken_By { get; set; }
        public string Pulse { get; set; }
        public string Temp { get; set; }
        public string RBS { get; set; }
    }
}
