//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class biovital
    {
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string BP { get; set; }
        public string Fasting { get; set; }
        public string Mass { get; set; }
        public Nullable<int> RecordedById { get; set; }
        public string RecordedBy { get; set; }
        public string Pulse { get; set; }
        public string Temp { get; set; }
        public string RBS { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
