//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim
    {
        public int ID { get; set; }
        public string HCP_Name { get; set; }
        public string Enrollee_Name { get; set; }
        public System.DateTime Date { get; set; }
        public string Item { get; set; }
        public string Price { get; set; }
        public string Remarks { get; set; }
        public string Amount_Word { get; set; }
        public string Enrollee_Code { get; set; }
    }
}
