//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientCompany()
        {
            this.patients = new HashSet<patient>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientGroupID { get; set; }
        public string Company { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> LMargin { get; set; }
        public Nullable<decimal> DMargin { get; set; }
    
        public virtual ClientGroup ClientGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient> patients { get; set; }
    }
}
