//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        public long ID { get; set; }
        public string Contractor { get; set; }
        public Nullable<System.DateTime> Contract_Date { get; set; }
        public string Contract_Title { get; set; }
        public string Contract_Category { get; set; }
        public string Paid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Amount_Paid { get; set; }
        public string Contact { get; set; }
        public string Contract_Status { get; set; }
        public string Bank { get; set; }
        public string Account { get; set; }
        public string Remark { get; set; }
    }
}
