//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Card_Number { get; set; }
        public string Parity { get; set; }
        public string Presentation { get; set; }
        public string Birth_Weight { get; set; }
        public string Sex { get; set; }
        public string Delivery_Type { get; set; }
        public string Condition { get; set; }
        public string APGAR_Score { get; set; }
        public Nullable<short> Fully_Dilate { get; set; }
        public string Delivered_By { get; set; }
        public Nullable<short> Vit_A1 { get; set; }
        public Nullable<short> Vit_A2 { get; set; }
        public Nullable<short> AVR { get; set; }
        public string Complication { get; set; }
        public string IPT_Doses { get; set; }
        public Nullable<short> PMTC { get; set; }
        public string Remark { get; set; }
        public string Refered_To { get; set; }
        public string Refered_From { get; set; }
        public Nullable<short> Still_Birth { get; set; }
        public string Multiple { get; set; }
    }
}
