//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string CardNumber { get; set; }
        public string Parity { get; set; }
        public string Presentation { get; set; }
        public string BirthWeight { get; set; }
        public string Sex { get; set; }
        public string DeliveryType { get; set; }
        public string Condition { get; set; }
        public string APGARScore { get; set; }
        public Nullable<short> FullyDilate { get; set; }
        public string DeliveredBy { get; set; }
        public Nullable<short> VitA1 { get; set; }
        public Nullable<short> VitA2 { get; set; }
        public Nullable<short> AVR { get; set; }
        public string Complication { get; set; }
        public string IPTDoses { get; set; }
        public Nullable<short> PMTC { get; set; }
        public string Remark { get; set; }
        public string ReferedTo { get; set; }
        public string ReferedFrom { get; set; }
        public Nullable<short> StillBirth { get; set; }
        public string Multiple { get; set; }
    }
}
