//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnosi
    {
        public long ID { get; set; }
        public string Card_Number { get; set; }
        public string Diagnosis { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Diagnosed_by { get; set; }
        public string Follow_Up { get; set; }
        public Nullable<long> AttID { get; set; }
    }
}
