//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnosis_type
    {
        public long ID { get; set; }
        public string Type { get; set; }
        public string Classification { get; set; }
        public string G_DRG { get; set; }
        public Nullable<decimal> Tarrif { get; set; }
        public Nullable<decimal> Tarrif__Catering_ { get; set; }
    }
}
