//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnosi
    {
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string CardNumber { get; set; }
        public string Diagnosis { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<int> DiagnosedByID { get; set; }
        public string DiagnosedBy { get; set; }
        public Nullable<int> AttID { get; set; }
    
        public virtual attendance attendance { get; set; }
    }
}
