//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class drug
    {
        public long ID { get; set; }
        public string Drug_Code { get; set; }
        public string Drug_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> Qnty { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Patient_Name { get; set; }
        public string Given_By { get; set; }
        public string Card_Number { get; set; }
        public Nullable<long> AttID { get; set; }
        public string Status { get; set; }
    }
}
