//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encounter
    {
        public long ID { get; set; }
        public string First_Name { get; set; }
        public string Surname { get; set; }
        public string Card_Number { get; set; }
        public string Facility { get; set; }
        public string Dept { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Diagnosis { get; set; }
        public string Service { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Provider { get; set; }
        public Nullable<decimal> Approved { get; set; }
        public Nullable<int> Patient { get; set; }
    }
}
