//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eregister
    {
        public long ID { get; set; }
        public string Card_Number { get; set; }
        public string HMO { get; set; }
        public string Code { get; set; }
        public string Family_Name { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Company { get; set; }
        public string Company_Code { get; set; }
        public string Status { get; set; }
        public string Position { get; set; }
        public string Designation { get; set; }
        public string Occupation { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Dept { get; set; }
        public string Sex { get; set; }
        public string Marital_Status { get; set; }
        public Nullable<long> Age { get; set; }
        public string Blood_Group { get; set; }
        public string National_ID { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<short> Diabetes { get; set; }
        public Nullable<short> Epilepsy { get; set; }
        public Nullable<short> Hypertension { get; set; }
        public Nullable<short> Sickle_Cell { get; set; }
        public Nullable<short> Allergies { get; set; }
        public string Others { get; set; }
        public Nullable<System.DateTime> Reg_Date { get; set; }
        public string NHIS_No { get; set; }
        public string NKin { get; set; }
        public string NKContact { get; set; }
        public string Scheme { get; set; }
        public string SchemeID { get; set; }
        public string Religion { get; set; }
        public string Postal_Address { get; set; }
        public string email { get; set; }
        public string District { get; set; }
        public string Sub_District { get; set; }
        public string Age_Group { get; set; }
        public string NHIS { get; set; }
    }
}
