//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab
    {
        public string Card { get; set; }
        public long ID { get; set; }
        public int id_test { get; set; }
        public string Sodium { get; set; }
        public string Potasium { get; set; }
        public string Chloride { get; set; }
        public string Bicarbonate { get; set; }
        public string Urea { get; set; }
        public string Creatitine { get; set; }
        public string Uric_Acid { get; set; }
        public string Calcium { get; set; }
        public string Phosphorus { get; set; }
        public string Total_Proteins { get; set; }
        public string Albumin { get; set; }
        public string Cholesterol { get; set; }
        public string Triglyceride { get; set; }
        public string HDL { get; set; }
        public string LDL { get; set; }
        public string SGOT { get; set; }
        public string SGPT { get; set; }
        public string Alk_Phos { get; set; }
        public string Amylase { get; set; }
        public string Acid_Phost { get; set; }
        public string Acid_Phosp { get; set; }
        public string PSA { get; set; }
        public string Fasting { get; set; }
        public string Random { get; set; }
        public string C2HPP { get; set; }
        public string GTT { get; set; }
        public string Total { get; set; }
        public string Direct { get; set; }
        public string Indirect { get; set; }
        public string Pregnancy_Test { get; set; }
        public string Stool_Occult_Blood { get; set; }
        public string Appearance { get; set; }
        public string PH { get; set; }
        public string Urobilinogen { get; set; }
        public string Colour { get; set; }
        public string Protein { get; set; }
        public string Nitrite { get; set; }
        public string Glucose { get; set; }
        public string Ascorbic_Acid { get; set; }
        public string Ketones { get; set; }
        public string SG { get; set; }
        public string Bilbrium { get; set; }
        public string Others { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
    }
}
