//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class labh
    {
        public long ID { get; set; }
        public string Card { get; set; }
        public int id_test { get; set; }
        public string Hb { get; set; }
        public string Pcv { get; set; }
        public string WBC { get; set; }
        public string MCHC { get; set; }
        public string ESR { get; set; }
        public string Relics { get; set; }
        public string Malaria_Parasite { get; set; }
        public string Diff_N { get; set; }
        public string Diff_L { get; set; }
        public string Diff_M { get; set; }
        public string Diff_E { get; set; }
        public string Diff_B { get; set; }
        public string Blood_Film { get; set; }
        public string Sicklin_Test { get; set; }
        public string Platelets_Count { get; set; }
        public string Bleeding_Time { get; set; }
        public string Clothing_Time { get; set; }
        public string Blood_Group { get; set; }
        public string Genotype { get; set; }
        public string Mantoux { get; set; }
        public string VDRL { get; set; }
        public string Hepatitis { get; set; }
        public string HBeAg { get; set; }
        public string Coombs_Direct { get; set; }
        public string Coombs_Indirect { get; set; }
        public string HIV { get; set; }
        public string Serum { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
    }
}
