//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class labp
    {
        public long ID { get; set; }
        public string Card { get; set; }
        public int id_test { get; set; }
        public string Macroscopy { get; set; }
        public string Microscopy { get; set; }
        public string Microfilaria { get; set; }
        public string Sputumaafb { get; set; }
        public string Time_Produced { get; set; }
        public string Time_Received { get; set; }
        public string Time_Analyzed { get; set; }
        public string Appearance { get; set; }
        public string Consistency { get; set; }
        public string Volume { get; set; }
        public string Active { get; set; }
        public string Sluggish { get; set; }
        public string Dead { get; set; }
        public string TCC { get; set; }
        public string MNC { get; set; }
        public string AC { get; set; }
        public string sComment { get; set; }
        public string Pus_Cells { get; set; }
        public string Epithelial_Cells { get; set; }
        public string RBC { get; set; }
        public string Casts { get; set; }
        public string Sperm_Cells { get; set; }
        public string Bacterial_Cells { get; set; }
        public string Yeast_Cells { get; set; }
        public string Trichomonas { get; set; }
        public string Haematobium { get; set; }
        public string cReport { get; set; }
        public string sReport { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
    }
}
