//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class labw
    {
        public long ID { get; set; }
        public string Card { get; set; }
        public int id_test { get; set; }
        public string wH { get; set; }
        public string wO { get; set; }
        public string wAH { get; set; }
        public string wAO { get; set; }
        public string wBH { get; set; }
        public string wBO { get; set; }
        public string wCH { get; set; }
        public string wCO { get; set; }
        public string wElisa { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
    }
}
