//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class monitor
    {
        public string User_Category { get; set; }
        public string User_Name { get; set; }
        public Nullable<System.DateTime> Date_Logged_On { get; set; }
        public string File_Used { get; set; }
        public string Details { get; set; }
        public Nullable<System.TimeSpan> Time_Logged_On { get; set; }
        public string company { get; set; }
    }
}
