//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrestock
    {
        public long ID { get; set; }
        public string Stock_Code { get; set; }
        public string Stock_Name { get; set; }
        public Nullable<System.DateTime> Stock_Date { get; set; }
        public Nullable<long> Qnty_Added { get; set; }
        public Nullable<long> Balance { get; set; }
        public string Received_By { get; set; }
        public string Supplier { get; set; }
        public string Location { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Unit_Cost { get; set; }
    }
}
