//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseNote
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string CardNumber { get; set; }
        public string Hour { get; set; }
        public Nullable<int> NurseID { get; set; }
        public string Nurse { get; set; }
        public string Note { get; set; }
    }
}
