//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nurse
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Card_Number { get; set; }
        public string Hour { get; set; }
        public string Nurse1 { get; set; }
        public string Note { get; set; }
    }
}
