//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operation
    {
        public long ID { get; set; }
        public string Type { get; set; }
        public string Indication { get; set; }
        public string Surgeon { get; set; }
        public string Assistant { get; set; }
        public string Nurse { get; set; }
        public string Anesthesia { get; set; }
        public string Anesthesist { get; set; }
        public string Procedure { get; set; }
        public string Outcome { get; set; }
        public string Instructions { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Card_Number { get; set; }
    }
}
