//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pension_manager
    {
        public string Pension_Managers { get; set; }
        public string Address { get; set; }
        public string Code { get; set; }
        public string company { get; set; }
    }
}
