//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pnc
    {
        public long ID { get; set; }
        public string Card_Number { get; set; }
        public string Birth_Weight { get; set; }
        public string PostN_Weight { get; set; }
        public string Mother_BP { get; set; }
        public string Fundus { get; set; }
        public string Perinium { get; set; }
        public string Lochia { get; set; }
        public string Condition { get; set; }
        public string Baby_Condition { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Physician { get; set; }
    }
}
