//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        public string Position_SortOrder { get; set; }
        public string Position1 { get; set; }
        public string Manager { get; set; }
        public string Report_T { get; set; }
        public string Position_Dept { get; set; }
        public string company { get; set; }
        public long id { get; set; }
    }
}
