//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisition
    {
        public long ID { get; set; }
        public string Stock_Code { get; set; }
        public string Stock_Name { get; set; }
        public Nullable<System.DateTime> Stock_Date { get; set; }
        public Nullable<long> Qnty_Req { get; set; }
        public Nullable<long> Qnty_Given { get; set; }
        public string Request_By { get; set; }
        public string Given_By { get; set; }
        public string Location { get; set; }
        public string Approved_By { get; set; }
        public string Category { get; set; }
        public string Destination { get; set; }
        public string Status { get; set; }
    }
}
