//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public long ID { get; set; }
        public string Stock_Code { get; set; }
        public string Stock_Name { get; set; }
        public Nullable<System.DateTime> Sales_Date { get; set; }
        public Nullable<decimal> Unit_Cost { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public Nullable<long> Qnty_Sold { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string Sold_By { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Paid { get; set; }
        public string Sold_To { get; set; }
        public string Sold_Name { get; set; }
        public string Entered_By { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Location { get; set; }
        public string Colour { get; set; }
        public Nullable<decimal> Bank_Amount { get; set; }
        public Nullable<decimal> Imprest_Amount { get; set; }
        public string Bank_Name { get; set; }
        public string Imprest_Detail { get; set; }
        public Nullable<System.DateTime> Bank_Date { get; set; }
        public Nullable<System.DateTime> Imprest_Date { get; set; }
        public string Receipt { get; set; }
        public string Slip_No { get; set; }
        public string cust_id { get; set; }
    }
}
