//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public string Staff_Number { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Othername { get; set; }
        public string Sex { get; set; }
        public string Initial_Rank { get; set; }
        public string Present_Rank { get; set; }
        public string Level { get; set; }
        public string Step { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Height { get; set; }
        public string Bank { get; set; }
        public string Acct_No { get; set; }
        public string Blood_Group { get; set; }
        public string Genotype { get; set; }
        public string Complexion { get; set; }
        public Nullable<short> In_Govt_Qtrs { get; set; }
        public string Bank_Location { get; set; }
        public string Bank_Branch { get; set; }
        public string email { get; set; }
        public Nullable<short> Previous_Conviction { get; set; }
        public Nullable<System.DateTime> First_Appt { get; set; }
        public Nullable<System.DateTime> Present_Appt { get; set; }
        public string State { get; set; }
        public string LGA { get; set; }
        public string Dept { get; set; }
        public string Home_Address { get; set; }
        public string Contact_Address { get; set; }
        public string Phone { get; set; }
        public string Prev_Location { get; set; }
        public string Present_Location { get; set; }
        public Nullable<System.DateTime> Pres_Location_Date { get; set; }
        public string Employment_Type { get; set; }
        public string Marital_Status { get; set; }
        public string Birth_Place { get; set; }
        public string Wife_Name { get; set; }
        public string Marriage_Date { get; set; }
        public string Wife_DoB { get; set; }
        public string Employment_Status { get; set; }
        public string Nationality { get; set; }
        public string Qualification { get; set; }
        public string Profession { get; set; }
        public Nullable<short> Confirmed { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> Date_Confirmed { get; set; }
        public string Pension_Managers { get; set; }
        public string Office { get; set; }
        public Nullable<decimal> Arrears { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> Pension_Amount { get; set; }
        public string Deformity { get; set; }
        public string Weight { get; set; }
        public string File_Number { get; set; }
        public Nullable<System.DateTime> Barrdate { get; set; }
        public Nullable<System.DateTime> Sworndate { get; set; }
        public Nullable<short> Chaffeur { get; set; }
        public Nullable<int> Cases { get; set; }
        public Nullable<int> Disposed { get; set; }
        public string Nat_Honour { get; set; }
        public Nullable<System.DateTime> GovtQtrs_Date { get; set; }
        public Nullable<System.DateTime> Chaffeur_Date { get; set; }
        public Nullable<System.DateTime> Ret_Date { get; set; }
        public Nullable<int> id { get; set; }
    }
}
