//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public long ID { get; set; }
        public string Stock_Code { get; set; }
        public string Category { get; set; }
        public string Brand_Name { get; set; }
        public string Stock_Name { get; set; }
        public string Description { get; set; }
        public string Manufacturer { get; set; }
        public string Supplier { get; set; }
        public Nullable<decimal> Unit_Cost { get; set; }
        public System.DateTime Manufactured_Date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<long> Reorder_Level { get; set; }
        public Nullable<long> Units_in_Stock { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Selling_Price { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> NHIS_Price { get; set; }
        public string Unit { get; set; }
    }
}
