//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class surgery
    {
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<System.DateTime> SurgeryDate { get; set; }
        public string CardNumber { get; set; }
        public string Operation { get; set; }
        public string Findings { get; set; }
        public string Anesthesia { get; set; }
        public string Anesthesist { get; set; }
        public string Assistant { get; set; }
        public string Surgeon { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
