//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rec
    {
        public int id_rec { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string Card { get; set; }
        public string transact { get; set; }
        public System.DateTime C_Date { get; set; }
    }
}
