//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_complaint
    {
        public int id_complaint { get; set; }
        public int id_category { get; set; }
        public string title_complaint { get; set; }
        public string codes { get; set; }
        public string Descriptors { get; set; }
    }
}
