//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFlowQueueAttendance
    {
        public int FQID { get; set; }
        public Nullable<int> FQAttID { get; set; }
        public Nullable<int> FQCurrentSTatus { get; set; }
        public Nullable<System.DateTime> FQTimeStamp { get; set; }
        public Nullable<int> FQLastUpdatedBy { get; set; }
        public Nullable<int> AttdID { get; set; }
        public Nullable<int> AttdPatientID { get; set; }
        public string AttCArdNumber { get; set; }
        public Nullable<int> AttDoctorID { get; set; }
        public Nullable<int> AttConsultingRoom { get; set; }
        public string Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public Nullable<bool> Attended { get; set; }
    }
}
