//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WardType
    {
        public int ID { get; set; }
        public string Ward { get; set; }
        public Nullable<int> Beds { get; set; }
        public string Remark { get; set; }
    }
}
