//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ward
    {
        public long ID { get; set; }
        public string Ward_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Activity_Type { get; set; }
        public string Card_Number { get; set; }
        public string Patient_Name { get; set; }
        public string Age { get; set; }
        public string Sex { get; set; }
        public string Official { get; set; }
        public string Designation { get; set; }
        public string Dept { get; set; }
        public string Hall { get; set; }
        public string Remark { get; set; }
        public string Posted_By { get; set; }
    }
}
